// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  url: 'https://compass-dev.tarento.com',
  token: '',
  frameworkName: 'compass_fw',
  channelId: '0138325860604395527',
  authToken: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0WEFsdFpGMFFhc1JDYlFnVXB4b2RvU2tLRUZyWmdpdCJ9.mXD7cSvv3Le6o_32lJplDck2D0IIMHnv0uJKq98YVwk',
  userToken:'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5YnBaRzhRQWF1SnZodUl2a2VqM2RVU2g3MUMzLTlvc21TdlhNeFBrbENRIn0.eyJqdGkiOiIzYmY5ZDhjNi02YWYyLTRkYTctYjhjOC01MDJmMTcwZjgzOTAiLCJleHAiOjE2ODg3MzYzMzEsIm5iZiI6MCwiaWF0IjoxNjg4NjkzMTMxLCJpc3MiOiJodHRwczovL2NvbXBhc3MtZGV2LnRhcmVudG8uY29tL2F1dGgvcmVhbG1zL3N1bmJpcmQiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiZjo0NDBjZTUzNi01NTYxLTRjYzgtOGZjMy1mZTRmMjUyMTBiZWY6YzIyNWI1ZTgtMGI5Mi00NWUxLWE1ZGMtODZjY2UwNWMzNTVhIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG1zIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiNTE5NzZhZTMtODg3NC00YjEyLThmZDAtYmJhZjM4ZjdhYjQxIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2NvbXBhc3MtZGV2LnRhcmVudG8uY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiIiLCJuYW1lIjoiQ29tcGFzc3JnQWRtaW4xIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiY29tcGFzc2FkbWluMSIsImdpdmVuX25hbWUiOiJDb21wYXNzcmdBZG1pbjEiLCJmYW1pbHlfbmFtZSI6IiIsImVtYWlsIjoiY28qKioqKioqKioqKkB5b3BtYWlsLmNvbSJ9.OLwQxOeuNd2HQQe31K76u2bHpqHaA1VxVxbD86A81WkVjoXleC0YttOG_R4W026yESU4wdv-Fh8jBLKtPC_4j4tgJ_2AhrsP8AmYhmYmbnlXIueMJGEGfcu3MJdsJdUmm3aVvUQlX6gOeAHLd2qvMgi9axAsVtufjNVe22cKHguEwZ35MzA6OE5Thkf4HwHAq2tvdH17mgRLsOxMBRf7HtRoJnnDnYUdNNcn-2kfAWO6aJ-COQUeaB5ioEBUkHSjSTEb__ExoZrobqYDBQR0cWVY2hTeaOBLTQ4F_eA91AX6hYc_y_dWHCbRPOaaLmBxaenBqoBwM1tWV9TNZZYRIw',
  isApprovalRequired: true
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
