export const labels = {
    flag: "flag",
    createNew: "Create New",
    build: "build",
    noData: "No Data Available",
    add: "add",
    pendingApproval: "Pending for Approval",
    date: "Date",
    more: "more...",
    rightArrow: "keyboard_arrow_right",
    alreadyExist: "Already Exist.",
    cancel: "Cancel",
    create: "Create",
    update: "Update",
    createCategories: "Create Categories",
    category: "Category",
    removeCircleOutline: "remove_circle_outline",
    close: "close",
    endPoint: "Enter End Point",
    token: "Enter Token",
    enterFrameworkName: "Enter Framework Name",
    frameworkName: "Framework Name",
    clear: "Clear",
    or: "Or",
    experienceTaxonomy: "Experience Taxonomy",
    playWithIt: "Let's Play with it",
    newConnection: "Create New Connection",
    categoryPreview: "Categories Preview",
    allFrac: "All Frac",
    treeView: "tree view...",
    categoryName: "Enter Category Name",
    name: "Enter Name",
    description: "Enter Description"
}